config/routes.rb
Rails.application.routes.draw do
  resources :invts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invt.rb
class Invt < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invts_controller.rb
class InvtsController < ApplicationController
  before_action :set_invt, only: [:show, :edit, :update, :destroy]

  # GET /invts
  # GET /invts.json
  def index
    @invts = Invt.all
  end

  # GET /invts/1
  # GET /invts/1.json
  def show
  end

  # GET /invts/new
  def new
    @invt = Invt.new
  end

  # GET /invts/1/edit
  def edit
  end

  # POST /invts
  # POST /invts.json
  def create
    @invt = Invt.new(invt_params)

    respond_to do |format|
      if @invt.save
        format.html { redirect_to @invt, notice: 'El producto fue almacenado exitosamented.' }
        format.json { render :show, status: :created, location: @invt }
      else
        format.html { render :new }
        format.json { render json: @invt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invts/1
  # PATCH/PUT /invts/1.json
  def update
    respond_to do |format|
      if @invt.update(invt_params)
        format.html { redirect_to @invt, notice: 'El producto fue actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @invt }
      else
        format.html { render :edit }
        format.json { render json: @invt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invts/1
  # DELETE /invts/1.json
  def destroy
    @invt.destroy
    respond_to do |format|
      format.html { redirect_to invts_url, notice: 'El producto fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invt
      @invt = Invt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invt_params
      params.require(:invt).permit(:producto, :existencia, :precio, :descripcion, :fecha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invts_helper.rb
module InvtsHelper
end

app/views/invts/_form.html.erb
<%= form_for(invt) do |f| %>
  <% if invt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invt.errors.count, "error") %> prohibited this invt from being saved:</h2>

      <ul>
      <% invt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <div class="field">
    <%= f.label :producto %>
    <%= f.text_field :producto %> 
  </div>

  <div class="field">
    <%= f.label :existencia %>
    <%= f.number_field :existencia %>
  </div>

  <div class="field">
    <%= f.label :precio %>
    <%= f.text_field :precio %>
  </div>

  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion %>
  </div>

  <div class="field">
    <%= f.label :fecha %>
    <%= f.date_select :fecha %>
  </div>
</div>



  <div class="btn btn-secondary" type="buttom">
  <%= f.submit :Realizar %>
  </div>
<% end %>

app/views/invts/edit.html.erb
<h1>Editar Inventario</h1>

<%= render 'form', invt: @invt %>

<%= link_to 'Editar', @invt %> |
<%= link_to 'Atras', invts_path %>

app/views/invts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventario</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Producto</th>
      <th>Existencia</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invts.each do |invt| %>
      <tr>
        <td><%= invt.producto %></td>
        <td><%= invt.existencia %></td>
        <td><%= invt.precio %></td>
        <td><%= invt.descripcion %></td>
        <td><%= invt.fecha %></td>
        <td><%= link_to 'Mostrar', invt %></td>
        <td><%= link_to 'Editar', edit_invt_path(invt) %></td>
        <td><%= link_to 'Eliminar', invt, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Producto', new_invt_path %>

app/views/invts/new.html.erb
<h1>Nuevo producto</h1>

<%= render 'form', invt: @invt %>

<%= link_to 'Atras', invts_path %>

app/views/invts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @invt.producto %>
</p>

<p>
  <strong>Existencia:</strong>
  <%= @invt.existencia %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @invt.precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @invt.descripcion %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @invt.fecha %>
</p>


<%= link_to 'Editar', edit_invt_path(@invt) %> |
<%= link_to 'Atras', invts_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventario</title>
 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

<div class="container">
  <!-- Content here -->
   <%= yield %>
</div>
  </body>
</html>